name: Sync Altered Knowledge to OpenAI Vector Store

on:
  push:
    branches: [ main ]
    paths:
      - 'SETS/**'
      - 'COLLECTION/**'
      - 'RULES/**'
      - 'tools/**'
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Run sync
        id: run_sync
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          VECTOR_STORE_NAME: "Altered Knowledge"
          # Optional (nach Schritt mit fester ID):
          VECTOR_STORE_ID: ${{ secrets.OPENAI_VECTOR_STORE_ID }}
        run: |
          python tools/sync_to_vector_store.py | tee sync.log
          VS_ID=$(grep -Eo 'VECTOR_STORE_ID=vs_[a-zA-Z0-9]+' sync.log | sed 's/.*=//')
          echo "vector_store_id=$VS_ID" >> $GITHUB_OUTPUT
